const sequelize = require('../config/db');

// Import models
const User = require('./User');
const Project = require('./Project');
const Site = require('./Site');
const ProgressReport = require('./ProgressReport');
const SitePhoto = require('./SitePhoto');
const Material = require('./Material');
const LabourAttendance = require('./LabourAttendance');
const Expense = require('./Expense');
const Notification = require('./Notification');
const Report = require('./Report');

// Define associations

// Project & Site
Project.hasMany(Site, { as: 'sites', foreignKey: 'projectId', onDelete: 'CASCADE' });
Site.belongsTo(Project, { as: 'project', foreignKey: 'projectId' });

// User & Site (Engineer assignment)
User.hasMany(Site, { as: 'assignedSites', foreignKey: 'engineerId', onDelete: 'SET NULL' });
Site.belongsTo(User, { as: 'engineer', foreignKey: 'engineerId' });

// Site & ProgressReport
Site.hasMany(ProgressReport, { as: 'progressReports', foreignKey: 'siteId', onDelete: 'CASCADE' });
ProgressReport.belongsTo(Site, { as: 'site', foreignKey: 'siteId' });

// User & ProgressReport (Reporter)
User.hasMany(ProgressReport, { as: 'submittedReports', foreignKey: 'reporterId', onDelete: 'SET NULL' });
ProgressReport.belongsTo(User, { as: 'reporter', foreignKey: 'reporterId' });

// ProgressReport & SitePhoto
ProgressReport.hasMany(SitePhoto, { as: 'photos', foreignKey: 'progressReportId', onDelete: 'CASCADE' });
SitePhoto.belongsTo(ProgressReport, { as: 'progressReport', foreignKey: 'progressReportId' });

// Site & Material
Site.hasMany(Material, { as: 'materials', foreignKey: 'siteId', onDelete: 'CASCADE' });
Material.belongsTo(Site, { as: 'site', foreignKey: 'siteId' });

// Site & LabourAttendance
Site.hasMany(LabourAttendance, { as: 'labourRecords', foreignKey: 'siteId', onDelete: 'CASCADE' });
LabourAttendance.belongsTo(Site, { as: 'site', foreignKey: 'siteId' });

// Site & Expense
Site.hasMany(Expense, { as: 'expenses', foreignKey: 'siteId', onDelete: 'CASCADE' });
Expense.belongsTo(Site, { as: 'site', foreignKey: 'siteId' });

// User & Expense (Logged by)
User.hasMany(Expense, { as: 'loggedExpenses', foreignKey: 'loggedBy', onDelete: 'SET NULL' });
Expense.belongsTo(User, { as: 'logger', foreignKey: 'loggedBy' });

// User & Notification
User.hasMany(Notification, { as: 'notifications', foreignKey: 'userId', onDelete: 'CASCADE' });
Notification.belongsTo(User, { as: 'user', foreignKey: 'userId' });

// Site & Report
Site.hasMany(Report, { as: 'reports', foreignKey: 'siteId', onDelete: 'CASCADE' });
Report.belongsTo(Site, { as: 'site', foreignKey: 'siteId' });

// User & Report (Generated by)
User.hasMany(Report, { as: 'generatedReports', foreignKey: 'generatedBy', onDelete: 'SET NULL' });
Report.belongsTo(User, { as: 'generator', foreignKey: 'generatedBy' });

module.exports = {
  sequelize,
  User,
  Project,
  Site,
  ProgressReport,
  SitePhoto,
  Material,
  LabourAttendance,
  Expense,
  Notification,
  Report,
};
